spring:
  # settings for profile
  profiles:
    active: local  # if you want to have the environment of the develop server, then it should be dev not local
    include: secret
  # settings for multipart data such as image

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB