#aws
cloud:
  aws:
    s3:
      bucket: umc-yorieter
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

## JWT Setting
# echo 'spring-backend-umc-project-security-jwt-secret-key' | base64
jwt:
  secret: ${JWT_SECRET}